#### Q1. Pandas version

What version of Pandas did you install?

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

In [3]:
data = pd.read_csv("car_fuel_efficiency_2026.csv")
data.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

#### Q2. Records count

How many records are in the dataset?

In [4]:
data.shape[0]

10000

#### Q3. Fuel types

How many fuel types are presented in the dataset?

In [5]:
data['fuel_type'].nunique()

3

In [6]:
data.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

#### Q4. Missing values

How many columns in the dataset have missing values?

In [7]:
data.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
(data.isnull().sum() > 0).sum()

np.int64(2)

#### Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [9]:
data.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [10]:
data[data.origin == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

#### Q6. Median value of horsepower

Find the median value of the horsepower column in the dataset.

Next, calculate the most frequent value of the same horsepower column.

Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

Now, calculate the median value of horsepower once again.

In [11]:
median_horsepower = data['horsepower'].median()
median_horsepower

np.float64(254.0)

In [12]:
most_frequent_value = data['horsepower'].mode()
most_frequent_value

0    252.0
Name: horsepower, dtype: float64

In [13]:
data['horsepower'] = data['horsepower'].fillna(most_frequent_value)
data['horsepower'].head()

0    243.0
1    272.0
2    267.0
3    258.0
4    304.0
Name: horsepower, dtype: float64

In [14]:
median_horsepower = data['horsepower'].median()
print(f'Median Value: {median_horsepower}')

Median Value: 254.0

No it hasn't changed

#### Q7. Sum of weights

Select all the cars from Asia

Select only columns vehicle_weight and model_year

Select the first 7 values

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Invert XTX.

Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

In [15]:
df_test = data[data.origin == 'Asia']
df_test.head(3)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9

In [16]:
df_test = data[data.origin == 'Asia'][['vehicle_weight', 'model_year']]

In [17]:
df_test[0:7]

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [18]:
#Get the underlying NumPy array
X = df_test[0:7].values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [19]:
#Matrix multiplication: X.T × X
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [20]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [21]:
# Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [22]:
# Calculate w
w = (XTX_inv @ X.T) @ y
w

array([0.13644777, 0.2327492 ])

In [23]:
# Sum of all elements
w.sum()

np.float64(0.36919696904925486)